# Generated by Django 5.1.5 on 2025-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaultimage.jpg', upload_to='profile_picture/'),
        ),
    ]
